=== ColinEberhardt/datahelix/schemas/src/main/resources/profileschema/0.1/datahelix.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://scottlogic.com/datahelix.json",
  "definitions": {
    "schemaVersion": {
      "type": "string",
      "title": "The version of the DataHelix profile schema",
      "pattern": "^[0-9]+[.][0-9]+$"
    },
    "temporal": {
      "type": "object",
      "additionalProperties": false,
      "required": ["date"],
      "properties": {
        "additionalProperties": false,
        "date": {
          "type": "string",
          "title": "an ISO 8610 compatible string denoting a date and time",
          "pattern": "^(?!0000)[0-9]{4}-([0][0-9]|[1][0-2])-([0-2][0-9]|3[01])T([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9][.][0-9]{3}$"
        }
      }
    },
    "fieldName": {
      "title": "The name of a field to generate data for",
      "type": "object",
      "additionalProperties": false,
      "required": ["name"],
      "properties": {
        "name": {"type": "string"}
      }
    },
    "constraint": {
      "oneOf": [
        {
          "$ref": "#/definitions/grammaticalConstraint"
        },
        {
          "$ref": "#/definitions/dataConstraint"
        }
      ]
    },
    "grammaticalConstraint": {
      "oneOf": [
        {
          "$ref": "#/definitions/notConstraint"
        },
        {
          "$ref": "#/definitions/anyOfConstraint"
        },
        {
          "$ref": "#/definitions/allOfConstraint"
        },
        {
          "$ref": "#/definitions/ifConstraint"
        }
      ]
    },
    "dataConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["field", "is"],
      "properties": {
        "field": {"type": "string"},
        "is": {
          "enum": [
            "ofType", "equalTo", "aValid", "inSet",
            "formattedAs", "matchingRegex", "containingRegex", "ofLength", "longerThan", "shorterThan",
            "null",
            "greaterThan", "lessThan", "greaterThanOrEqualTo", "lessThanOrEqualTo", "granularTo",
            "after", "afterOrAt", "before", "beforeOrAt"
          ]
        }
      },
      "anyOf": [
        {
          "if": {
            "properties": {"is": {"enum": ["after", "afterOrAt", "before", "beforeOrAt"]}}
          },
          "then": {
            "properties": {"value": {"$ref": "#/definitions/temporal"}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "equalTo"}}
          },
          "then": {
            "properties": {"value": {}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "ofType"}}
          },
          "then": {
            "properties": {"value": {"enum": ["numeric", "string", "temporal"]}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "inSet"}}
          },
          "then": {
            "properties": {"values": {"type": "array", "minItems": 2}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "null"}}
          },
          "then": {
            "properties": {"not": {}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "formattedAs"}}
          },
          "then": {
            "properties": {"value": {"pattern": "^%.+$"}}
          }
        },
        {
          "if": {
            "properties": {"is": {"enum": ["matchingRegex", "containingRegex"]}}
          },
          "then": {
            "properties": {"value": {"type": "string"}}
          }
        },
        {
          "if": {
            "properties": {
              "is": {
                "enum": ["shorterThan", "longerThan", "greaterThan", "lessThan", "greaterThanOrEqualTo", "lessThanOrEqualTo", "granularTo"]
              }
            }
          },
          "then": {
            "properties": {"value": {"type": "number"}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "aValid"}}
          },
          "then": {
            "properties": {"value": {"const": "ISIN"}}
          }
        }
      ]
    },
    "notConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["not"],
      "properties": {
        "not": {"$ref": "#/definitions/constraint"}
      }
    },
    "anyOfConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["anyOf"],
      "properties": {
        "anyOf": {
          "type": "array",
          "minItems": 2,
          "items": {
            "$ref": "#/definitions/constraint"
          }
        }
      }
    },
    "allOfConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["allOf"],
      "properties": {
        "allOf": {
          "type": "array",
          "minItems": 2,
          "items": {
            "$ref": "#/definitions/constraint"
          }
        }
      }
    },
    "ifConstraint": {
      "type": "object",
      "required": ["if", "then"],
      "properties": {
        "if": {
          "$ref": "#/definitions/constraint"
        },
        "then": {
          "$ref": "#/definitions/constraint"
        },
        "else": {
          "$ref": "#/definitions/constraint"
        }
      }
    }
  },
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "fields", "rules"],
  "title": "The Scott Logic DataHelix Profile Schema",
  "properties": {
    "additionalProperties": false,
    "schemaVersion": {
      "$ref": "#/definitions/schemaVersion"
    },
    "description": {
      "type": "string",
      "title": "A description of what data the profile is modelling"
    },
    "fields": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "additionalItems": false,
      "title": "Defines the fields that data will be produced for. field names must begin with an alphabetic character.",
      "items": {
        "$ref": "#/definitions/fieldName"
      }
    },
    "rules": {
      "type": "array",
      "minItems": 1,
      "additionalItems": false,
      "title": "The Rules defining the data to be output",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["constraints"],
        "title": "A set of Rule objects.",
        "properties": {
          "rule": {
            "type": "string",
            "title": "A collection of constraints. Test case generation revolves around rules, in that the generator will output a separate dataset for each rule, wherein each row violates the rule in a different way."
          },
          "constraints": {
            "type": "array",
            "minItems": 1,
            "items": {"$ref": "#/definitions/constraint"}
          }
        }
      }
    }
  }
}

=== ColinEberhardt/datahelix/generator/resources/partitioning-tests/daisy-chained-rules/profile.json
{
  "schemaVersion": "v3",
  "description": "Testing a profile that contains multiple rule dependencies",
  "fields": [
    { "name": "FirstField" },
    { "name": "SecondField" },
    { "name": "ThirdField" },
    { "name": "FourthField" },
    { "name": "FifthField" },
    { "name": "SixthField" },
    { "name": "SeventhField" },
    { "name": "EighthField" }
  ],
  "rules": [{
    "rule": "FirstField",
    "constraints": [{
      "field": "FirstField",
      "is": "inSet",
      "values": [
        "A",
        "B",
        "C",
        "D",
        "E"
      ]
    },{
      "not": {
        "field": "FirstField",
        "is": "null"
      }
    },{
      "if": {
        "field": "SecondField",
        "is": "equalTo",
        "value": "P"
      },
      "then": {
        "field": "FirstField",
        "is": "inSet",
        "values": [
          "A",
          "B",
          "C"
        ]
      }
    }]
  },{
    "rule": "SecondField",
    "constraints": [{
      "field": "SecondField",
      "is": "ofType",
      "value": "string"
    },{
      "not": {
        "field": "SecondField",
        "is": "null"
      }
    },{
      "if": {
        "field": "ThirdField",
        "is": "inSet",
        "values": [
          1,
          2,
          3
        ]
      },
      "then": {
        "field": "SecondField",
        "is": "inSet",
        "values": [
          "O",
          "P",
          "Q"
        ]
      }
    }]
  },{
    "rule": "ThirdField",
    "constraints": [{
      "field": "ThirdField",
      "is": "inSet",
      "values": [
        1,
        2,
        3,
        4,
        5
      ]
    },{
      "not": {
        "field": "ThirdField",
        "is": "null"
      }
    }]
  },{
    "rule": "FourthField",
    "constraints": [{
      "field": "FourthField",
      "is": "ofType",
      "value": "numeric"
    },{
      "if": {
        "allOf": [{
          "field": "FifthField",
          "is": "greaterThan",
          "value": 20
        },{
          "field": "FifthField",
          "is": "lessThan",
          "value": 50
        }]
      },
      "then": {
        "field": "FourthField",
        "is": "inSet",
        "values": [
          5,
          10,
          12,
          15
        ]
      }
    }]
  },{
    "rule": "FifthField",
    "constraints": [{
      "field": "FifthField",
      "is": "inSet",
      "values": [
        5,
        10,
        20,
        25,
        35,
        40,
        50,
        60,
        65,
        70
      ]
    }]
  },{
    "rule": "SixthField",
    "constraints": [{
      "field": "SixthField",
      "is": "ofType",
      "value": "string"
    },{
      "not": {
        "field": "SixthField",
        "is": "null"
      }
    },{
        "if": {
        "field": "EighthField",
        "is": "inSet",
        "values": [
          "A1",
          "A2"
        ]
      },
      "then": {
        "field": "SixthField",
        "is": "inSet",
        "values": [
          "B1",
          "B3"
        ]
      }
    }]
  },{
    "rule": "SeventhField",
    "constraints": [{
      "field": "SeventhField",
      "is": "ofType",
      "value": "string"
    },{
      "if": {
        "field": "SixthField",
        "is": "inSet",
        "values": [
          "B1",
          "B3"
        ]
      },
      "then": {
        "field": "SeventhField",
        "is": "equalTo",
        "value": "Test"
      }
    }]
  },{
    "rule": "EighthField",
    "constraints": [{
      "field": "EighthField",
      "is": "inSet",
      "values": [
        "A1",
        "A2",
        "A3",
        "A4"
      ]
    },{
      "not": {
        "field": "EighthField",
        "is": "null"
      }
    }]
  }]
}

=== ColinEberhardt/datahelix/generator/resources/partitioning-tests/deeper-tree/profile.json
{
  "schemaVersion": "v3",
  "description": "Testing a deeper tree for partitioning",
  "fields":
  [
    { "name": "UserType" },
    { "name": "Post" },
    { "name": "PostType" },
    { "name": "Action" },
    { "name": "Topic" },
    { "name": "Event" },
    { "name": "Duration" }
  ],
  "rules": [{
    "rule": "UserType",
    "constraints": [{
      "field": "UserType",
      "is": "inSet",
      "values": [
        "A",
        "B",
        "C",
        "D",
        "E"
      ]
    },{
      "not": {
        "field": "UserType",
        "is": "null"
      }
    }]
  },{
    "rule": "PostType",
    "constraints": [{
      "field": "PostType",
      "is": "inSet",
      "values": [
        "PostType1",
        "PostType2",
        "PostType3",
        "PostType4"
      ]
    },{
      "not": {
        "field": "PostType",
        "is": "null"
      }
    },{
      "if": {
        "field": "UserType",
        "is": "equalTo",
        "value": "A"
      },
      "then": {
        "field": "PostType",
        "is": "inSet",
        "values": [
          "PostType1",
          "PostType4"
        ]
      }
    },{
      "if": {
        "field": "UserType",
        "is": "inSet",
        "values": [
          "C",
          "D"
        ]
      },
      "then": {
        "field": "PostType",
        "is": "inSet",
        "values": [
          "PostType2",
          "PostType3"
        ]
      }
    }]
  },{
    "rule": "Post",
    "constraints": [{
      "field": "Post",
      "is": "ofType",
      "value": "string"
    },{
      "not": {
        "field": "Post",
        "is": "null"
      }
    },{
      "if": {
        "field": "PostType",
        "is": "equalTo",
        "value": "PostType1"
      },
      "then": {
        "field": "Post",
        "is": "shorterThan",
        "value": 20
      }
    }]
  },{
    "rule": "Action",
    "constraints": [{
      "field": "Action",
      "is": "inSet",
      "values": [
        "ActionA",
        "ActionB",
        "ActionC"
      ]
    },{
      "if": {
        "field": "UserType",
        "is": "equalTo",
        "value": "C"
      },
      "then": {
        "if": {
          "field": "PostType",
          "is": "equalTo",
          "value": "PostType2"
        },
        "then": {
          "field": "Action",
          "is": "equalTo",
          "value": "ActionB"
        }
      }
    }]
  },{
    "rule": "Topic",
    "constraints": [{
      "field": "Topic",
      "is": "ofType",
      "value": "string"
    },{
      "field": "Topic",
      "is": "shorterThan",
      "value": 30
    },{
      "not": {
        "field": "Topic",
        "is": "null"
      }
    },{
      "if": {
        "field": "Event",
        "is": "inSet",
        "values": [
          "FirstEvent",
          "SecondEvent"
        ]
      },
      "then": {
        "field": "Topic",
        "is": "inSet",
        "values": [
          "InterestingTopic",
          "TechnicalTopic"
        ]
      }
    }]
  },{
    "rule": "Event",
    "constraints": [{
      "field": "Event",
      "is": "inSet",
      "values": [
        "FirstEvent",
        "SecondEvent",
        "ThirdEvent"
      ]
    }]
  },{
    "rule": "Duration",
    "constraints": [{
      "field": "Duration",
      "is": "ofType",
      "value": "numeric"
    },{
      "not": {
        "field": "Duration",
        "is": "null"
      }
    },{
      "if": {
        "field": "Event",
        "is": "equalTo",
        "value": "FirstEvent"
      },
      "then": {
        "if": {
          "field": "Topic",
          "is": "equalTo",
          "value": "InterestingTopic"
        },
        "then": {
          "field": "Duration",
          "is": "equalTo",
          "value": "60"
        }
      }
    }]
  }]
}

=== ColinEberhardt/datahelix/generator/resources/partitioning-tests/unique-data-sets/profile.json
{
  "schemaVersion": "v3",
  "description": "Tests that a profile that contains all unique data sets can be correctly partitioned",
  "fields":
  [
    { "name": "Asset" },
    { "name": "AssetType" },
    { "name": "AccountType" },
    { "name": "AuditLevel" },
    { "name": "AccountLevel" },
    { "name": "FundValue" },
    { "name": "FundType" }
  ],
  "rules": [{
    "rule": "Asset",
    "constraints": [{
      "field": "Asset",
      "is": "inSet",
      "values": [
        "First Wealthy Asset",
        "Second Wealthy Asset",
        "Third Wealthy Asset",
        "First Average Asset",
        "Second Average Asset",
        "Third Average Asset",
        "Fourth Average Asset",
        "First Low Asset",
        "Second Low Asset"
      ]
    },{
      "not": {
        "field": "Asset",
        "is": "null"
      }
    },{
      "if": {
        "field": "AssetType",
        "is": "equalTo",
        "value": "High"
      },
      "then": {
        "field": "Asset",
        "is": "inSet",
        "values": [
          "First Wealthy Asset",
          "Second Wealthy Asset",
          "Third Wealthy Asset"
        ]
      }
    },{
      "if": {
        "field": "AssetType",
        "is": "equalTo",
        "value": "Average"
      },
      "then": {
        "field": "Asset",
        "is": "inSet",
        "values": [
          "First Average Asset",
          "Second Average Asset",
          "Third Average Asset",
          "Fourth Average Asset"
        ]
      }
    },{
      "if": {
        "field": "AssetType",
        "is": "equalTo",
        "value": "Low"
      },
      "then": {
        "field": "Asset",
        "is": "inSet",
        "values": [
          "First Low Asset",
          "Second Low Asset"
        ]
      }
    }]
  },{
    "rule": "AssetType",
    "constraints": [{
      "field": "AssetType",
      "is": "inSet",
      "values": [
        "High",
        "Average",
        "Low"
      ]
    },{
      "not": {
        "field": "AssetType",
        "is": "null"
      }
    }]
  },{
    "rule": "AccountType",
    "constraints": [{
      "field": "AccountType",
      "is": "inSet",
      "values": [
        "AccountType1",
        "AccountType2",
        "AccountType3",
        "AccountType4",
        "AccountType5"
      ]
    },{
      "not": {
        "field": "AccountType",
        "is": "null"
      }
    }]
  },{
    "rule": "AuditLevel",
    "constraints": [{
      "field": "AuditLevel",
      "is": "inSet",
      "values": [
        "Maximum",
        "Minimum",
        "Custom"
      ]
    },{
      "not": {
        "field": "AuditLevel",
        "is": "null"
      }
    }]
  },{
    "rule": "AccountLevel",
    "constraints": [{
      "field": "AccountLevel",
      "is": "inSet",
      "values": [
        "AccountLevel1",
        "AccountLevel2",
        "AccountLevel3"
      ]
    },{
      "not": {
        "field": "AccountLevel",
        "is": "null"
      }
    },{
      "if": {
        "field": "AccountType",
        "is": "inSet",
        "values": [
          "AccountType1",
          "AccountType3"
        ]
      },
      "then": {
        "field": "AccountLevel",
        "is": "equalTo",
        "value": "AccountLevel1"
      }
    },{
      "if": {
        "field": "AccountType",
        "is": "inSet",
        "values": [
          "AccountType2",
          "AccountType4"
        ]
      },
      "then": {
        "field": "AccountLevel",
        "is": "equalTo",
        "value": "AccountLevel2"
      }
    },{
      "if": {
        "field": "AccountType",
        "is": "equalTo",
        "value": "AccountType5"
      },
      "then": {
        "field": "AccountLevel",
        "is": "equalTo",
        "value": "AccountLevel3"
      }
    }]
  },{
    "rule": "FundValue",
    "constraints": [{
      "field": "FundValue",
      "is": "inSet",
      "values": [
        10,
        15,
        25,
        30,
        50,
        65,
        70,
        73,
        80,
        100
      ]
    },{
      "not": {
        "field": "FundValue",
        "is": "null"
      }
    },{
      "if": {
        "field": "FundType",
        "is": "equalTo",
        "value": "FundType1"
      },
      "then": {
        "field": "FundValue",
        "is": "inSet",
        "values": [
          10,
          15,
          50,
          65
        ]
      }
    },{
      "if": {
        "field": "FundType",
        "is": "equalTo",
        "value": "FundType2"
      },
      "then": {
        "field": "FundValue",
        "is": "inSet",
        "values": [
          30,
          50,
          70,
          73,
          100
        ]
      }
    },{
      "if": {
        "field": "FundType",
        "is": "equalTo",
        "value": "FundType3"
      },
      "then": {
        "field": "FundValue",
        "is": "inSet",
        "values": [
          10,
          15,
          30,
          65,
          73,
          80,
          100
        ]
      }
    }]
  },{
    "rule": "FundType",
    "constraints": [{
      "field": "FundType",
      "is": "inSet",
      "values": [
        "FundType1",
        "FundType2",
        "FundType3"
      ]
    },{
      "not": {
        "field": "FundType",
        "is": "null"
      }
    }]
  }]
}
